### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Jeydin** [animemoeus/waifu-animemoeus#122]
Is the API open source?

**Comment by animemoeus** [comment]
> Is the API open source?

yep 🙂

[https://api.animemoe.us/waifu](https://api.animemoe.us/waifu)

**Comment by Jeydin** [comment]
That's just compiled JSON output, where's the code that gets the images and such -_-

**Comment by ArifzynXD** [comment]
can you give me vercel.json?

**Comment by animemoeus** [comment]
> can you give me vercel.json?

wdym? i dont have that file 🤔

**Comment by animemoeus** [comment]
> That's just compiled JSON output, where's the code that gets the images and such -_-

HYG 🚀

- https://github.com/animemoeus/backend
- https://github.com/animemoeus/backend/tree/master/waifu
