### ISSUE TITLE
Update to NextJS 14

### ISSUE THREAD

**Issue by animemoeus** [animemoeus/waifu-animemoeus#335]

**Comment by NawinKumarSharma** [comment]
@animemoeus , can you assign me? i want to work on this?

**Comment by animemoeus** [comment]
> @animemoeus , can you assign me? i want to work on this?

Hello @NawinKumarSharma, you have to fork this repo :grin: 

https://github.com/animemoeus/waifu-animemoeus/issues/337#issuecomment-2389019585

**Comment by A-4-Atom** [comment]
@animemoeus 
Hi, I'll start converting the pages router to app router, when it's done I'll create a PR. :)

**Comment by NawinKumarSharma** [comment]
@animemoeus hey, i have nearly completed the task
