### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by animemoeus** [animemoeus/waifu-animemoeus#337]
Add linter to CI/CD for checking the code.

---

Example:

https://github.com/animemoeus/backend/actions/runs/11022627416/job/30738386979?pr=413
![image](https://github.com/user-attachments/assets/0565bb1e-1dbc-4835-8fc5-5ae5d000cbad)

**Comment by ShehzadAhm** [comment]
Hi @animemoeus, can you assign this issue?

**Comment by animemoeus** [comment]
wdym? 🤔

**Comment by animemoeus** [comment]
> Hi @animemoeus, can you assign this issue?

wdym? 🤔

**Comment by A-4-Atom** [comment]
@animemoeus You have to assign this issue to someone, so they can start working on it.

**Comment by animemoeus** [comment]
Hello, everyone! You can fork the repo and create a pull request from your fork.

Here’s an example: https://github.com/animemoeus/waifu-animemoeus/pull/338
